import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script"; // 1. Importojmë Script nga Next.js
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lumovia",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    sizes: '512x512',
    type: 'image/x-icon',
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}

        {/* --- SKRIPTET E REKLAMAVE SHTOHEN KËTU --- */}
        <div className="w-full overflow-hidden flex flex-col items-center justify-center max-w-[100vw]">

        {/* 1. Skripti i parë */}
        <Script
          src="https://pl31524309.profitableratecpmnetwork.com/a6/28/46/a628465f46378ec561d25b66152b062f.js"
          strategy="lazyOnload"
        />

        {/* 2. Skripti i dytë (Banner me atOptions) */}
        <Script
          id="high-revenue-options"
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{
            __html: `
              atOptions = {
                'key' : 'de269c4f7b18325b576be2fc5cec8dcf',
                'format' : 'iframe',
                'height' : 90,
                'width' : 728,
                'params' : {}
              };
            `,
          }}
        />
        <Script
          src="https://www.highrevenueformat.com/de269c4f7b18325b576be2fc5cec8dcf/invoke.js"
          strategy="lazyOnload"
        />

        {/* 3. Skripti i tretë */}
        <Script
          src="https://pl31524311.profitableratecpmnetwork.com/f5/83/a1/f583a1ce8bd1a0fa814c54e068bd5015.js"
          strategy="lazyOnload"
        />

        {/* 4. Skripti i katërt (Direkt link ose mund ta trajtoni si skript nëse kërkohet) */}
        {/* Për lidhjen e thjeshtë që dërguat, nëse është link i zakonshëm, mund të përdorni një tag <a> diku në faqe sipas dëshirës, ose nëse është skript, vendosni src-në */}

        {/* 5. Skripti i pestë me container div */}
        <Script
          async="async"
          data-cfasync="false"
          src="https://pl31524313.profitableratecpmnetwork.com/db49430d3df8ec5834bce3b81912e3cb/invoke.js"
          strategy="lazyOnload"
        />

        {/* Div-i i kërkuar për reklamën e fundit */}
        <div id="container-db49430d3df8ec5834bce3b81912e3cb" className="max-w-full overflow-hidden"></div>
        </div>

      </body>
    </html>
  );
}